# nixpacks.toml  (repo root)

providers = ["node"]

# --- install phase -----------------------------------------------------------
[phases.install]
cmds = [
  # standard install, prod-only deps
  "npm install --omit=dev --unsafe-perm"
]

# --- start phase -------------------------------------------------------------
[start]
cmd = "node loader.js --no-daemon --port $PORT"
